export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";

export interface EndpointCatalogEntry {
  name: string;
  title: string;
  category: string;
  method: HttpMethod;
  path: string;
  contentType?: string;
  description?: string;
  docUrl: string;
}

const DOC_BASE =
  "https://docs.thinkingdata.cn/ta-manual/latest/technical_document/open_api";

export const endpointCatalog: EndpointCatalogEntry[] = [
  {
    name: "sql_sync_query",
    title: "SQL 同步查询",
    category: "数据自定义查询 API",
    method: "POST",
    path: "/querySql",
    contentType: "application/x-www-form-urlencoded",
    description: "通过 SQL 查询数据，适合较小结果集。",
    docUrl: `${DOC_BASE}/data_api.html`,
  },
  {
    name: "sql_submit",
    title: "提交 SQL 查询任务",
    category: "数据自定义查询 API",
    method: "POST",
    path: "/open/submit-sql",
    contentType: "application/x-www-form-urlencoded",
    description: "提交异步 SQL 查询任务，返回 taskId。",
    docUrl: `${DOC_BASE}/data_api.html`,
  },
  {
    name: "sql_execute",
    title: "执行 SQL 分页查询",
    category: "数据自定义查询 API",
    method: "POST",
    path: "/open/execute-sql",
    contentType: "application/x-www-form-urlencoded",
    description: "执行 SQL 分页查询，返回分页 meta 信息。",
    docUrl: `${DOC_BASE}/data_api.html`,
  },
  {
    name: "sql_task_info",
    title: "查询 SQL 任务状态",
    category: "数据自定义查询 API",
    method: "GET",
    path: "/open/sql-task-info",
    description: "根据 taskId 查询 SQL 任务执行状态。",
    docUrl: `${DOC_BASE}/data_api.html`,
  },
  {
    name: "sql_result_page",
    title: "下载 SQL 分页结果",
    category: "数据自定义查询 API",
    method: "POST",
    path: "/open/sql-result-page",
    description: "根据 taskId 和 pageId 获取分页数据。",
    docUrl: `${DOC_BASE}/data_api.html`,
  },
  {
    name: "sql_cancel_task",
    title: "取消 SQL 任务",
    category: "数据自定义查询 API",
    method: "POST",
    path: "/open/cancel-sql-task",
    description: "取消尚未结束的 SQL 查询任务。",
    docUrl: `${DOC_BASE}/data_api.html`,
  },

  {
    name: "event_analyze",
    title: "事件分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/event-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/event_query_api.html`,
  },
  {
    name: "event_user_list",
    title: "事件分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/event-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/event_query_api.html`,
  },
  {
    name: "event_analyze_download",
    title: "事件分析全量下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/event-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/event_query_api.html`,
  },
  {
    name: "event_user_list_download",
    title: "事件分析用户列表下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/event-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/event_query_api.html`,
  },
  {
    name: "retention_analyze",
    title: "留存分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/retention-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/retention_query_api.html`,
  },
  {
    name: "retention_user_list",
    title: "留存分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/retention-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/retention_query_api.html`,
  },
  {
    name: "retention_analyze_download",
    title: "留存分析全量下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/retention-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/retention_query_api.html`,
  },
  {
    name: "retention_user_list_download",
    title: "留存分析用户列表下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/retention-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/retention_query_api.html`,
  },
  {
    name: "funnel_analyze",
    title: "漏斗分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/funnel-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/funnel_query_api.html`,
  },
  {
    name: "funnel_user_list",
    title: "漏斗分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/funnel-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/funnel_query_api.html`,
  },
  {
    name: "funnel_analyze_download",
    title: "漏斗分析全量下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/funnel-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/funnel_query_api.html`,
  },
  {
    name: "funnel_user_list_download",
    title: "漏斗分析用户列表下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/funnel-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/funnel_query_api.html`,
  },
  {
    name: "distribution_analyze",
    title: "分布分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/distribution-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/distribution_query_api.html`,
  },
  {
    name: "distribution_user_list",
    title: "分布分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/distribution-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/distribution_query_api.html`,
  },
  {
    name: "distribution_analyze_download",
    title: "分布分析全量下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/distribution-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/distribution_query_api.html`,
  },
  {
    name: "distribution_user_list_download",
    title: "分布分析用户列表下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/distribution-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/distribution_query_api.html`,
  },
  {
    name: "path_analyze",
    title: "路径分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/path-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/path_query_api.html`,
  },
  {
    name: "path_user_list",
    title: "路径分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/path-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/path_query_api.html`,
  },
  {
    name: "interval_analyze",
    title: "间隔分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/interval-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/interval_query_api.html`,
  },
  {
    name: "interval_user_list",
    title: "间隔分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/interval-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/interval_query_api.html`,
  },
  {
    name: "interval_analyze_download",
    title: "间隔分析全量下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/interval-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/interval_query_api.html`,
  },
  {
    name: "interval_user_list_download",
    title: "间隔分析用户列表下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/interval-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/interval_query_api.html`,
  },
  {
    name: "user_prop_analyze",
    title: "用户属性分析查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/user-prop-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/user_prop_query_api.html`,
  },
  {
    name: "user_prop_user_list",
    title: "用户属性分析用户列表",
    category: "模型查询 API",
    method: "POST",
    path: "/open/user-prop-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/user_prop_query_api.html`,
  },
  {
    name: "user_event_list",
    title: "用户事件列表查询",
    category: "模型查询 API",
    method: "POST",
    path: "/open/user-event-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/user_prop_query_api.html`,
  },
  {
    name: "user_prop_analyze_download",
    title: "用户属性分析全量下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/user-prop-analyze",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/user_prop_query_api.html`,
  },
  {
    name: "user_prop_user_list_download",
    title: "属性分析用户列表下载",
    category: "模型查询 API",
    method: "POST",
    path: "/open/streaming-download/user-prop-user-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/query_api/user_prop_query_api.html`,
  },
  {
    name: "metric_list",
    title: "查询可用指标列表",
    category: "指标查询 API",
    method: "POST",
    path: "/open/metric-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/metric_api.html`,
  },
  {
    name: "metric_data",
    title: "查询指标数据",
    category: "指标查询 API",
    method: "POST",
    path: "/open/metric-data",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/metric_api.html`,
  },

  {
    name: "user_cluster_add",
    title: "添加条件分群或标签",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/user-cluster-add",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "user_cluster_list",
    title: "分群和标签列表查询",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/user-cluster-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "user_cluster_detail",
    title: "分群或标签详情查询",
    category: "用户分群和标签 API",
    method: "GET",
    path: "/open/user-cluster-detail",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "user_cluster_update_by_name",
    title: "根据名称更新条件分群或标签定义",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/user-cluster-update-by-name",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "user_cluster_refresh_by_name",
    title: "根据名称刷新条件分群或标签",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/user-cluster-refresh-by-name",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "user_cluster_refresh_progress_by_name",
    title: "查询刷新进度",
    category: "用户分群和标签 API",
    method: "GET",
    path: "/open/user-cluster-refresh-progress-by-name",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "delete_user_cluster_by_name",
    title: "根据名称删除分群或标签",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/delete-user-cluster-by-name",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "import_id_cluster_add",
    title: "创建上传 ID 分群或标签",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/import-id-cluster-add",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "import_id_cluster_modify_by_name",
    title: "根据名称修改上传 ID 分群或标签",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/import-id-cluster-modify-by-name",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "user_cluster_import_file",
    title: "上传 ID 文件",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/import",
    contentType: "multipart/form-data",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },
  {
    name: "tag_date_batch_refresh",
    title: "异步批量刷新标签日期版本",
    category: "用户分群和标签 API",
    method: "POST",
    path: "/open/tag-date-batch-refresh",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_cluster_api.html`,
  },

  {
    name: "dict_create",
    title: "创建维度表或维度字典",
    category: "维度表/元数据管理 API",
    method: "POST",
    path: "/open/dict-create",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dimension_table_api.html`,
  },
  {
    name: "datatable_upload_file",
    title: "数据表文件上传",
    category: "数据表 API",
    method: "POST",
    path: "/open/datatable/uploadFile",
    contentType: "multipart/form-data",
    docUrl: `${DOC_BASE}/dataset_api.html`,
  },
  {
    name: "datatable_create",
    title: "创建数据表",
    category: "数据表 API",
    method: "POST",
    path: "/open/datatable/createDatatable",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dataset_api.html`,
  },
  {
    name: "datatable_update",
    title: "更新已有数据表",
    category: "数据表 API",
    method: "POST",
    path: "/open/datatable/updateDatatable",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dataset_api.html`,
  },
  {
    name: "datatable_bind_associated_property",
    title: "关联数据表与主属性",
    category: "数据表 API",
    method: "POST",
    path: "/open/datatable/bindAssociatedProperty",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dataset_api.html`,
  },
  {
    name: "datatable_unbind_associated_property",
    title: "解除数据表与主属性关联关系",
    category: "数据表 API",
    method: "POST",
    path: "/open/datatable/unbindAssociatedProperty",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dataset_api.html`,
  },
  {
    name: "get_sql_for_user_search",
    title: "生成查询用户的 SQL 语句",
    category: "生成 SQL 语句 API",
    method: "POST",
    path: "/open/get-sql-for-user-search",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/generate_sql_api.html`,
  },

  {
    name: "list_event_meta",
    title: "事件元信息列表",
    category: "元数据管理 API",
    method: "GET",
    path: "/open/list-event-meta",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "list_props",
    title: "属性列表",
    category: "元数据管理 API",
    method: "GET",
    path: "/open/list-props",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "update_event_info",
    title: "修改事件显示名",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/update-event-info",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "update_prop_info",
    title: "修改属性显示名",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/update-prop-info",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "create_virtual_event",
    title: "创建虚拟事件",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/create-virtual-event",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "get_virtual_event_by_name",
    title: "查询虚拟事件",
    category: "元数据管理 API",
    method: "GET",
    path: "/open/get-virtual-event-by-name",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "delete_virtual_event_by_name",
    title: "删除虚拟事件",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/delete-virtual-event-by-name",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "create_sql_prop",
    title: "新建虚拟属性",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/create-sql-prop",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "get_sql_prop_by_name",
    title: "查询虚拟属性",
    category: "元数据管理 API",
    method: "GET",
    path: "/open/get-sql-prop-by-name",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "delete_sql_prop_by_name",
    title: "删除 SQL 虚拟属性",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/delete-sql-prop-by-name",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },
  {
    name: "delete_dict_props",
    title: "删除维度属性",
    category: "元数据管理 API",
    method: "POST",
    path: "/open/delete-dict-props",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/meta_data_manage_api.html`,
  },

  {
    name: "manage_reports",
    title: "查询 Root 账号的报表列表",
    category: "看板报表管理 API",
    method: "GET",
    path: "/open/manage-reports",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "list_project_reports",
    title: "查询项目报表列表",
    category: "看板报表管理 API",
    method: "GET",
    path: "/open/list-project-reports",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "report_batch_delete",
    title: "批量删除报表",
    category: "看板报表管理 API",
    method: "POST",
    path: "/open/report-batch-del",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "import_dashboards",
    title: "导入看板",
    category: "看板报表管理 API",
    method: "POST",
    path: "/open/import-dashboards",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "get_space_dashboards_by_space_name",
    title: "查询空间 ID 和看板列表",
    category: "看板报表管理 API",
    method: "GET",
    path: "/open/get-space-dashboards-by-space-name",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "get_space_members_by_space_name",
    title: "查询空间 ID 和成员权限列表",
    category: "看板报表管理 API",
    method: "GET",
    path: "/open/get-space-members-by-space-name",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "update_space",
    title: "更新空间成员权限列表",
    category: "看板报表管理 API",
    method: "POST",
    path: "/open/update-space",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "delete_space",
    title: "删除空间",
    category: "看板报表管理 API",
    method: "POST",
    path: "/open/delete-space",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },
  {
    name: "delete_dashboard_from_space",
    title: "删除空间看板",
    category: "看板报表管理 API",
    method: "POST",
    path: "/open/delete-dashboard-from-space",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/dashboard_report_manage_api.html`,
  },

  {
    name: "batch_create_auth_user_and_set_roles",
    title: "批量创建用户角色",
    category: "用户管理 API",
    method: "POST",
    path: "/open/batch-create-auth-user-and-set-roles",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "create_sso_user",
    title: "创建 SSO 用户",
    category: "用户管理 API",
    method: "GET",
    path: "/open/create/ssoUser",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "create_project_role",
    title: "新建项目角色",
    category: "用户管理 API",
    method: "POST",
    path: "/open/create-project-role",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "create_user_group",
    title: "创建用户分组",
    category: "用户管理 API",
    method: "POST",
    path: "/open/create-user-group",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "delete_auth_user_from_project",
    title: "从项目中删除用户",
    category: "用户管理 API",
    method: "POST",
    path: "/open/delete-auth-user-from-project",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "delete_auth_user_from_system",
    title: "从系统中删除用户",
    category: "用户管理 API",
    method: "POST",
    path: "/open/delete-auth-user-from-system",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "delete_project_role",
    title: "删除项目角色",
    category: "用户管理 API",
    method: "POST",
    path: "/open/delete-project-role",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "delete_user_group",
    title: "删除用户分组",
    category: "用户管理 API",
    method: "POST",
    path: "/open/delete-user-group",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "get_auth_user_info_by_login_name",
    title: "查询单个用户信息，包括角色",
    category: "用户管理 API",
    method: "GET",
    path: "/open/get-auth-user-info-by-login-name",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "get_auth_user_status",
    title: "查询用户账户状态",
    category: "用户管理 API",
    method: "GET",
    path: "/open/get-auth-user-status",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "get_base_role_functions",
    title: "获取基本角色功能列",
    category: "用户管理 API",
    method: "GET",
    path: "/open/get-base-role-functions",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "get_project_role_by_role_desc",
    title: "获取项目角色详情",
    category: "用户管理 API",
    method: "GET",
    path: "/open/get-project-role-by-role-desc",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "get_user_group_by_name",
    title: "查询用户组 ID 和成员列表",
    category: "用户管理 API",
    method: "GET",
    path: "/open/get-user-group-by-name",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "list_auth_users_by_login_names",
    title: "查询用户 ID",
    category: "用户管理 API",
    method: "POST",
    path: "/open/list-auth-users-by-login-names",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "member_lock",
    title: "用户冻结",
    category: "用户管理 API",
    method: "POST",
    path: "/open/member-lock",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "member_unlock",
    title: "用户解冻",
    category: "用户管理 API",
    method: "POST",
    path: "/open/member-unlock",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "share_add_black",
    title: "添加黑名单",
    category: "用户管理 API",
    method: "POST",
    path: "/open/share/add-black",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "share_add_black_group_list",
    title: "设置黑名单组",
    category: "用户管理 API",
    method: "POST",
    path: "/open/share/add-black-group-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "share_add_black_list",
    title: "批量添加黑名单 CSV",
    category: "用户管理 API",
    method: "POST",
    path: "/open/share/add-black-list",
    contentType: "multipart/form-data",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "share_cancel_black",
    title: "删除黑名单",
    category: "用户管理 API",
    method: "POST",
    path: "/open/share/cancel-black",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "share_download_share_black",
    title: "下载黑名单",
    category: "用户管理 API",
    method: "POST",
    path: "/open/share/download-share-black",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "unbind_auth_user_mfa",
    title: "解绑用户 MFA",
    category: "用户管理 API",
    method: "POST",
    path: "/open/unbind-auth-user-mfa",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "update_project_role",
    title: "修改项目角色",
    category: "用户管理 API",
    method: "POST",
    path: "/open/update-project-role",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },
  {
    name: "update_user_group",
    title: "更新用户组成员列表",
    category: "用户管理 API",
    method: "POST",
    path: "/open/update-user-group",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/user_manage_api.html`,
  },

  {
    name: "project_list",
    title: "用户项目列表",
    category: "项目管理 API",
    method: "POST",
    path: "/open/project-list",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/project_manage_api.html`,
  },
  {
    name: "generate_project_app_id",
    title: "创建新项目并生成 appId",
    category: "项目管理 API",
    method: "POST",
    path: "/open/project/generate-project-app-id",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/project_manage_api.html`,
  },
  {
    name: "update_project_info",
    title: "更新项目信息",
    category: "项目管理 API",
    method: "POST",
    path: "/open/project/update-project-info",
    contentType: "application/json",
    docUrl: `${DOC_BASE}/project_manage_api.html`,
  },
];

export const endpointCatalogByName = new Map(
  endpointCatalog.map((entry) => [entry.name, entry]),
);

export function searchEndpointCatalog(query?: string) {
  if (!query?.trim()) {
    return endpointCatalog;
  }

  const normalized = query.trim().toLowerCase();
  return endpointCatalog.filter((entry) => {
    return [
      entry.name,
      entry.title,
      entry.category,
      entry.path,
      entry.description ?? "",
    ]
      .join(" ")
      .toLowerCase()
      .includes(normalized);
  });
}
